<a href="https://colab.research.google.com/github/iamsaroj2058/ML-Daily-Updates/blob/main/100_day_Ml(day_13).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This is day 13 of  100 day ML

# Steps we perform
0. Preprocess + EDA + Feature Selection
1. Extract input and output cols
2. Scale the value
3. Train test split
4. Train model
5. Evaluate the model/model selection
6. Deploy the model

In [3]:
import numpy as np
import pandas as  pd
#importing numpy and  pandas  library

In [15]:
df = pd.read_csv('/content/placement.csv')

In [16]:
df.head()
#df.head()
#shows only the first 5 rows of the DataFrame by default.

   Unnamed: 0  cgpa     iq  placement
0           0   6.8  123.0          1
1           1   5.9  106.0          0
2           2   5.3  121.0          0
3           3   7.4  132.0          1
4           4   5.8  142.0          0

In [17]:
# Preprocessing --> this is the step  where we  make  our raw data set into a clean , usable format before training a machine learning mode.

df= df.iloc[:,1:]
# this   function select all row  but  column starting from  1

In [18]:
df.head()

   cgpa     iq  placement
0   6.8  123.0          1
1   5.9  106.0          0
2   5.3  121.0          0
3   7.4  132.0          1
4   5.8  142.0          0